#!/usr/bin/env ansible-playbook

- name: Deploy WireGuard VPN stack
  hosts: all
  become: true

  vars_files:
    - custom.yml
    - secret.yml

  handlers:
    - name: Import global handlers
      ansible.builtin.import_tasks: handlers/main.yml

  roles:
    - role: system
      tags:
        - system

    - role: docker
      tags:
        - docker

    - role: ufw
      tags:
        - ufw

    - role: fail2ban
      tags:
        - fail2ban

    - role: wireguard
      tags:
        - wireguard

    - role: authelia
      tags:
        - authelia

    - role: bunkerweb
      tags:
        - bunkerweb
