#!/usr/bin/env ansible-playbook

- hosts: all
  become: true

  vars_files:
    - custom.yml
    - secret.yml

  handlers:
    - import_tasks: handlers/main.yml

 # pre_tasks:
 #   - set_fact:
 #       aws: "{{ lookup('ansible.builtin.env', 'AWS_EC2') == 'true' }}"

  roles:
    - role: system
      tags:
        - system

    - role: docker
      tags:
        - docker

    - role: fail2ban
      tags:
        - fail2ban

    - role: ufw
      tags:
        - ufw

    - role: authelia
      tags:
        - authelia

    - role: bunkerweb
      tags:
        - bunkerweb

    - role: wireguard
      tags:
        - wireguard
