---
- name: Restart authelia
  community.docker.docker_container:
    name: authelia
    restart: true

- name: Restart wg-easy
  community.docker.docker_container:
    name: wg-easy
    restart: true

- name: Restart bunkerweb
  community.docker.docker_container:
    name: bunkerweb
    restart: true

- name: Source .bashrc
  ansible.builtin.command: source /home/{{ username }}/.bashrc
  changed_when: false
