---
- name: Install Docker and the compose plugin
  community.general.pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Ensure group docker exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add username to group docker
  ansible.builtin.user:
    name: "{{ username }}"
    groups:
      - docker
    append: true

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker
    state: present

- name: Make sure Docker is running and enabled
  ansible.builtin.systemd:
    name: docker
    daemon_reload: true
    state: started
    enabled: true

- name: Create the WireGuard network
  community.docker.docker_network:
    name: wg_network
